//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimsWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ECDB_EWDFINALEntities : DbContext
    {
        public ECDB_EWDFINALEntities()
            : base("name=ECDB_EWDFINALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EC_ADMINISTRATOR> EC_ADMINISTRATOR { get; set; }
        public virtual DbSet<EC_CLAIMS> EC_CLAIMS { get; set; }
        public virtual DbSet<EC_COORDINATOR> EC_COORDINATOR { get; set; }
        public virtual DbSet<EC_MANAGER> EC_MANAGER { get; set; }
        public virtual DbSet<FACULTY> FACULTies { get; set; }
        public virtual DbSet<STUDENT> STUDENTs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Upload> Uploads { get; set; }
    }
}
