//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimsWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class EC_COORDINATOR
    {
        public string EC_CoodId { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string StudentId { get; set; }
        public string FacultyId { get; set; }
        public Nullable<int> ClaimId { get; set; }
    
        public virtual EC_CLAIMS EC_CLAIMS { get; set; }
        public virtual FACULTY FACULTY { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
