//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimsWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upload
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string FileName { get; set; }
        public string ContentType { get; set; }
        public Nullable<long> Size { get; set; }
        public byte[] Data { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ClaimId { get; set; }
    
        public virtual EC_CLAIMS EC_CLAIMS { get; set; }
    }
}
